version: '3'

services:

  rabbitmq:
    container_name: "rabbitmq"
    hostname: localhost
    user: root
    build:
      context: ./rabbitmq/
      dockerfile: Dockerfile
#    volumes:
#      - "./.docker/rabbitmq/volumes/etc/:/etc/rabbitmq/"
#      - "./.docker/rabbitmq/volumes/data/:/var/lib/rabbitmq/"
#      - "./.docker/rabbitmq/volumes/logs/:/var/log/rabbitmq/"
    ports:
      - "5672:5672"
      - "15672:15672"
      - "15692:15692"

  msg_producer:
    container_name: "msg_producer"
    hostname: localhost
    build:
      context: ./msgProducer/
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    volumes:
      - "./.docker/msgProducer/volumes/logs:/logs"
    depends_on:
      - rabbitmq

  slack_consumer:
    container_name: "slack_consumer"
    hostname: localhost
    build:
      context: ./slackConsumer/
      dockerfile: Dockerfile
    ports:
      - "8082:8080"
    environment:
      SLACK_URL: ${SLACK_URL}
    volumes:
      - "./.docker/slackConsumer/volumes/logs:/logs"
    depends_on:
      - rabbitmq

  sms_consumer:
    container_name: "sms_consumer"
    hostname: localhost
    build:
      context: ./smsConsumer/
      dockerfile: Dockerfile
    ports:
      - "8084:8080"
    environment:
      VONAGE_API_KEY: ${VONAGE_API_KEY}
      VONAGE_API_SECRET: ${VONAGE_API_SECRET}
      VONAGE_PHONE_NUMBER: ${VONAGE_PHONE_NUMBER}
    volumes:
      - "./.docker/smsConsumer/volumes/logs:/logs"
    depends_on:
      - rabbitmq

  email_consumer:
    container_name: "email_consumer"
    hostname: localhost
    build:
      context: ./mailingConsumer/
      dockerfile: Dockerfile
    ports:
      - "8083:8080"
    environment:
      - MAILTRAP_USERNAME=${MAILTRAP_USERNAME}
      - MAILTRAP_PASSWORD=${MAILTRAP_PASSWORD}
    volumes:
      - "./.docker/mailingConsumer/volumes/logs:/logs"
    depends_on:
      - rabbitmq

  prometheus:
    container_name: "prometheus"
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    environment:
      GF_SERVER_ROOT_URL: http://localhost:3000
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: secret
    depends_on:
      - rabbitmq

  grafana:
    container_name: "grafana"
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - ./.docker/grafana/grafana-storage:/var/lib/grafana
      - ./.docker/grafana/provisioning/:/etc/grafana/provisioning
    environment:
      GF_SERVER_ROOT_URL: http://localhost:3000
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: secret
    depends_on:
      - rabbitmq
