server:
  port: 8083

application:
  developer: Nizami Islamovs
  version: v 1.0.0
  deploymentdate: 2018-09-11 21:15:29
  support.email: nizamiislamovs@gmail.com
  description: Slack consumer mcs
  title: Slack consumer mcs

spring:
  mail:
    host: smtp.mailtrap.io
    port: 2525
    username: ${MAILTRAP_USERNAME}
    password: ${MAILTRAP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
          starttls:
            enable: true
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest
    virtual-host: /
    publisher-returns: true
    template:
      mandatory: true
      retry:
        enabled: true
        initial-interval: 1000
        max-attempts: 3
        max-interval: 10000
        multiplier: 1.0
    listener:
      simple:
        concurrency: 10
        max-concurrency: 10
        prefetch: 1
        auto-startup: true
        default-requeue-rejected: true

email:
  from: "rabbitmq.do-not-reply@gmail.com"
  reply.to: <do-not-reply>
  to: nizami.islamovs.s@gmail.com
  subject.prefix: New message for you